#include "setup.h"

void initClockGate() {
	//PORT BCDE
	SIM->SCGC5 |= SIM_SCGC5_PORTE_MASK | SIM_SCGC5_PORTD_MASK | SIM_SCGC5_PORTC_MASK | SIM_SCGC5_PORTB_MASK;

	//UART
	SIM->SCGC4 |= SIM_SCGC4_UART2_MASK;
	
	//Timer0, Timer 1 and Timer 2
	SIM->SCGC6 = (SIM_SCGC6_TPM0_MASK) | (SIM_SCGC6_TPM1_MASK) | (SIM_SCGC6_TPM2_MASK);
}

void initMotorPWM() {
	
	SIM->SOPT2 &= ~SIM_SOPT2_TPMSRC_MASK;
	SIM->SOPT2 |= SIM_SOPT2_TPMSRC(1); //MCGFLLCLK MCGPLLCLK/2
	
	PORTE->PCR[LEFT_FORWARD] &= ~PORT_PCR_MUX_MASK; //Mode 3 for E
	PORTE->PCR[LEFT_FORWARD] |= PORT_PCR_MUX(3);
	PORTE->PCR[LEFT_REVERSE] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[LEFT_REVERSE] |= PORT_PCR_MUX(3);
	
	PORTC->PCR[RIGHT_FORWARD] &= ~PORT_PCR_MUX_MASK; //Mode 4 for C
	PORTC->PCR[RIGHT_FORWARD] |= PORT_PCR_MUX(4);
	PORTC->PCR[RIGHT_REVERSE] &= ~PORT_PCR_MUX_MASK;
	PORTC->PCR[RIGHT_REVERSE] |= PORT_PCR_MUX(4);
	TPM0->MOD = 7500;
	
	TPM0_SC &= ~((TPM_SC_CMOD_MASK) | (TPM_SC_PS_MASK));
	TPM0_SC |= (TPM_SC_CMOD(1) | TPM_SC_PS(7));
	TPM0_SC &= ~(TPM_SC_CPWMS_MASK);
  
	//Left, PTC29-CH2-LeftRev, PTC30-CH3-LeftFwd
	TPM0_C2SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
	TPM0_C2SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
	TPM0_C3SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
	TPM0_C3SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
	
	//Right, PTC1-CH0-RigFwd, PTC2-CH1-RigRev
	TPM0_C0SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
	TPM0_C0SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
	TPM0_C1SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
	TPM0_C1SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
}
